### ISSUE TITLE
Installation file provided did not correctly set path for convpot

### ISSUE THREAD

**Issue by darkwraith** [ahpohl/convpot#6]
After installation using the Convpot-1.1.1-win32.exe the path was not correctly set. Caused issues when called by plotpot. Fix can be done manually by adding C:\Program Files (x86)\Convpot v1.1.1 to the windows path as described here: https://www.computerhope.com/issues/ch000549.htm

**Comment by ahpohl** [comment]
Works for me. Tested under Windows 10 for both system path and current user. Which Windows version did you try?

**Comment by ahpohl** [comment]
Please download the latest windows release v1.1.7 and test again.

**Comment by darkwraith** [comment]
I'm running Windows 10 Home with a 64 bit x64 processor. I tested the new 1.1.7 32bit installer (after removing my old path information) and it did add the path "C:\Program Files (x86)\Convpot v1.1.7\bin" which the previous installation didn't for some reason.

**Comment by ahpohl** [comment]
great. thanks for yor feedback.
